name: 更新节目单

on:
  schedule:
    - cron: '20 0 * * *'   # 每天 00:20
    - cron: '50 09 * * *'  # 每天 9:50
    - cron: '35 14 * * *'  # 每天 14:35
  workflow_dispatch:  # 支持手动触发
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y wget gzip

      - name: Download and extract EPG file
        run: |
          # 下载gzip压缩文件
          wget https://github.com/kuke31/xmlgz/raw/main/e.xml.gz -O e.xml.gz
       
          # 解压文件
          gunzip -f e.xml.gz
          # 检查文件是否成功解压
          if [ -f e.xml ]; then
            echo "EPG file extracted successfully"
          else
            echo "Failed to extract EPG file"
            exit 1
          fi

      - name: Commit and push sorted file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add e.xml
          git commit -m "Update sorted channels" || echo "No changes to commit"
          git push
